image: smartbcity/gitlab-ci-jdk8:1.2.0

stages:
  - build
  - verify
  - version
  - package
  - push

variables:
  BRANCH_VERSION: "experimental"
  MASTER_VERSION: "next"
  PROFILES_ACTIVE: "gitlab"

.version-tag:
  stage: version
  image: smartbcity/gitlab-ci-semantic-versioning:1.2.0
  script:
    - make -f /opt/city.smartb/semantic-versioning/Makefile -e BRANCH_NAME=$CI_COMMIT_REF_NAME next_version >> version.build
  artifacts:
    paths:
      - version*

.version-next-tag:
  stage: version
  image: smartbcity/gitlab-ci-semantic-versioning:1.2.0
  script:
    - make -f /opt/city.smartb/semantic-versioning/Makefile next_version >> version.build
  artifacts:
    paths:
      - version*

.verify:
  stage: verify
  before_script:
    - CONTAINER_NAME=$(docker ps --format '{{.Names}}' --filter name=$HOSTNAME*)
    - docker network connect bclannet-it $CONTAINER_NAME
  script:
    - make test

.package:
  image: smartbcity/gitlab-ci-yarn:1.2.0
  stage: package
  script:
    - export VERSION_BUILD=$(cat version.build)
    - make package -e VERSION=${VERSION_BUILD}

.push:
  stage: push
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - export VERSION_BUILD=$(cat version.build)
    - make push -e VERSION=${VERSION_BUILD}

.onlyBranch: &onlyBranch
  only:
    refs:
      - branches
  except:
    refs:
      - master

.onlyMaster: &onlyMaster
  only:
    refs:
      - master

version-branch:
  <<: *onlyBranch
  extends: .version-next-tag
  after_script:
    - echo $BRANCH_VERSION > version.build
    - echo "//////////////////////////////"
    - echo "Version is "+ $(cat version.build)
    - echo "//////////////////////////////"

verify-branch:
  <<: *onlyBranch
  extends: .verify

package-branch:
  <<: *onlyBranch
  extends: .package
  artifacts:
    paths:
      - version*

push-branch:
  <<: *onlyBranch
  extends: .push
  when: manual

version-master:
  <<: *onlyMaster
  extends: .version-next-tag
  after_script:
    - echo $MASTER_VERSION > version.build
    - echo "//////////////////////////////"
    - echo "Version is "+ $(cat version.build)
    - echo "//////////////////////////////"

verify-master:
  <<: *onlyMaster
  extends: .verify

package-master:
  <<: *onlyMaster
  extends: .package

push-master:
  <<: *onlyMaster
  extends: .push
  when: manual

version-tags:
  extends: .version-tag
  only:
    - tags

verify-tags:
  extends: .verify
  only:
    - tags

package-tags:
  extends: .package
  only:
    - tags

push-tags:
  extends: .push
  only:
    - tags
